// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SingleClipMessage = { command: string, clipName: string, fadeDuration: number | null, panPosition: number | null, panSpread: number | null, volume: number | null, };
